### PR TITLE
Storybook added

### PR DESCRIPTION
**Pull request by makimenko**
-Storybook support added to the project (storybook.js.org)
- Allows easy to develop components in isolation
- Easy to mock sample data/behavior

### CODE REVIEW

**Comment by ComFreek** [comment]
Cool, didn't know about Storybook. Have you tried running it?

`npm storybook` gives me

```
PS P:\angular-template-for-threejs> npx storybook

 Storybook's CLI - The simplest way to add a storybook to your project.

 • Detecting project type. ✓
    Unsupported Project type. (code: UNDETECTED)
    Visit https://storybook.js.org for more information.
```

**Comment by makimenko** [comment]
> Cool, didn't know about Storybook. Have you tried running it?
Yep, please run:
```
npm run storybook
```

NOTE: npx storybook is for automatic installation/integration (already done)

**Comment by ComFreek** [comment]
Thanks, that way it works like a charme -- except for the mesh component story, but you figured that already :)

**Comment by ComFreek** [comment]
Thanks, that way it works like a charme -- except for the mesh component story, but you figured that already :)

I added a line in the README on this usage.

**Pull request merged**
